#!/bin/bash
git pull
cp -rf ~/git/front-streamer/* ~/webapps/front_stream/
cd ~/webapps/front_stream/
npm install
source .env
forever stop $PWD/app.coffee
if [[ ! -f ~/.forever/front_streamer.log ]]; then
  forever -l front_streamer.log --append start -c coffee $PWD/app.coffee
else
  forever -la front_streamer.log --append start -c coffee $PWD/app.coffee
fi
