#!/bin/bash
git pull
cp -rf ~/git/front-streamer/* ~/webapps/front_stream/
cd ~/webapps/front_stream/
npm install
source .env
forever stop $PWD/app.coffee
rm ~/.forever/front_streamer.log
forever -la front_streamer.log start -c coffee $PWD/app.coffee
